name: Build

on:
  push:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://sampleautoamtiontestraj.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN_FOR_CI_CD_WORKSHOP }}
  REACT_APP_API_BASE_URL: http://localhost:3001
  GIT_COMMIT: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}

jobs:
  publish-to-pact-flow:
    runs-on: ubuntu-latest
    name: Publish pacts
    steps:
      - name: pacts
        uses: rajnavakotiikea/publish-pacts@main
        with:
          pact_file_dir: ${PWD}/pacts
          consumer_app_version: ${{ github.sha }}
          tag: ${{ github.ref_name }}
          broker_base_url: https://sampleautoamtiontestraj.pactflow.io
          broker_token: GglUlzHa8Egn_fpkhzZQLw


#  publish-to-pact-flow:
#    runs-on: ubuntu-latest
#    name: Publish pacts
#    steps:
#      - name: webhook
#        uses: rajnavakotiikea/pact-command-execution@main
#        with:
#          action: create
#          webhook_type: consumer_commit_status
#          description: git commit status webhook for pactflow-example-consumer
#          organization: rajnavakotiikea
#          repository: example-provider
#          github_personal_access_token : ${{ secrets.ACCESS_TOKEN }}
#          broker_base_url: https://sampleautoamtiontestraj.pactflow.io
#          broker_token: GglUlzHa8Egn_fpkhzZQLw
#          consumer: pactflow-example-consumer
#          provider: pactflow-example-provider
#          contract_content_changed: true
#          contract_published: true

#          no_contract_content_changed: true
#          provider_label: pact-example-provider-label
#          consumer_label: pact-example-consumer-label
#          no_contract_published: true
#          provider_verification_published: true
#          no_provider_verification_published: true
#          provider_verification_failed: true
#          no_provider_verification_failed: true
#          provider_verification_succeeded: true
#          no_provider_verification_succeeded: true
#          contract_requiring_verification_published: true
#          no_contract_requiring_verification_published: true


#      - name: Publish pact
#        uses: ingka-group-digital/dsm-workflows/actions/publish_contract@pact-contract-test-composite-actions
#        with:
#          pact_broker_base_url: PACT_BROKER_BASE_URL
#          pact_broker_token: PACT_BROKER_TOKEN
#          git_commit: GIT_COMMIT
#          git_branch: GIT_REF

#  test:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        pact_provider:
#          [
#            # "pactflow-example-bi-directional-provider-dredd",
#            # "pactflow-example-bi-directional-provider-restassured",
#            # "pactflow-example-bi-directional-provider-postman",
#            "pactflow-example-provider",
#          ]
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2-beta
#        with:
#          node-version: "12"
#      - name: Install for ${{ matrix.pact_provider }}
#        run: npm i
#      - name: Test for ${{ matrix.pact_provider }}
#        env:
#          PACT_PROVIDER: ${{ matrix.pact_provider }}
#        run: make test
#      - name: Publish pacts for${{ matrix.pact_provider }}
#        run: GIT_BRANCH=${GIT_REF:11} make publish_pacts
#        env:
#          PACT_PROVIDER: ${{ matrix.pact_provider }}

  # Runs on branches as well, so we know the status of our PRs
#  can-i-deploy:
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#      - uses: actions/checkout@v2
#      - run: docker pull pactfoundation/pact-cli:latest
#      - name: Can I deploy?
#        run: GIT_BRANCH=${GIT_REF:11} make can_i_deploy

  # Only deploy from master
#  deploy:
#    runs-on: ubuntu-latest
#    needs: can-i-deploy
#    steps:
#      - uses: actions/checkout@v2
#      - run: docker pull pactfoundation/pact-cli:latest
#      - name: Deploy
#        run: GIT_BRANCH=${GIT_REF:11} make deploy
#        if: github.ref == 'refs/heads/master'
