name: Test pipeline

on:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://sampleautoamtiontestraj.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN_FOR_CI_CD_WORKSHOP }}
  GIT_COMMIT: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}

jobs:
  publish-to-pact-flow:
    runs-on: ubuntu-latest
    name: Publish pacts
    steps:
      - name: Publish pact
        uses: ingka-group-digital/dsm-workflows/actions/publish_contract@pact-contract-test-composite-actions
        with:
          pact_broker_base_url: PACT_BROKER_BASE_URL
          pact_broker_token: PACT_BROKER_TOKEN
          git_commit: GIT_COMMIT
          git_branch: GIT_REF
